// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject2016.subsystems;

import org.usfirst.frc2337.RobotProject2016.commands.Chassis_TankDrive;
import org.usfirst.frc2337.RobotProject2016.RobotMap;
import org.usfirst.frc2337.RobotProject2016.commands.*;

import edu.wpi.first.wpilibj.AnalogAccelerometer;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 *
 */
public class ChassisPID extends PIDSubsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final AnalogGyro gyro = RobotMap.chassisPIDgyro;
    private final PowerDistributionPanel powerDistributionPanel = RobotMap.chassisPIDpowerDistributionPanel;
    private final Encoder driveEncoder = RobotMap.chassisPIDdriveEncoder;
    private final Ultrasonic ultrasonicSensor = RobotMap.chassisPIDultrasonicSensor;
    private final AnalogAccelerometer accelerometer = RobotMap.chassisPIDaccelerometer;
    private final CANTalon chassisLeft1 = RobotMap.chassisPIDchassisLeft1;
    private final CANTalon chassisLeft2 = RobotMap.chassisPIDchassisLeft2;
    private final CANTalon chassisLeft3 = RobotMap.chassisPIDchassisLeft3;
    private final CANTalon chassisRight1 = RobotMap.chassisPIDchassisRight1;
    private final CANTalon chassisRight2 = RobotMap.chassisPIDchassisRight2;
    private final CANTalon chassisRight3 = RobotMap.chassisPIDchassisRight3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    RobotDrive robotDrive = RobotMap.chassisDrive;  
    // Initialize your subsystem here
    public ChassisPID() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("ChassisPID", 1.0, 0.0, 0.0);
        setAbsoluteTolerance(0.2);
        getPIDController().setContinuous(false);
        LiveWindow.addActuator("ChassisPID", "PIDSubsystem Controller", getPIDController());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        RobotMap.chassisPIDchassisLeft1.enableBrakeMode(false);
    	RobotMap.chassisPIDchassisLeft2.enableBrakeMode(false);
    	RobotMap.chassisPIDchassisLeft3.enableBrakeMode(false);
    	
    	RobotMap.chassisPIDchassisRight1.enableBrakeMode(false);
    	RobotMap.chassisPIDchassisRight2.enableBrakeMode(false);
    	RobotMap.chassisPIDchassisRight3.enableBrakeMode(false);
        // Use these to get going:
        // setSetpoint() -  Sets where the PID controller should move the system
        //                  to
        // enable() - Enables the PID controller.
    }
    public void tankDrive(double leftValue, double rightValue) {
    	robotDrive.tankDrive(leftValue, rightValue, true);
    }
    public void arcadeDrive(double leftValue, double turnValue) {
    	robotDrive.arcadeDrive(leftValue, turnValue, true);
    }
    public void setBrakeMode(boolean type) {
    	RobotMap.chassisPIDchassisLeft1.enableBrakeMode(type);
    	RobotMap.chassisPIDchassisLeft2.enableBrakeMode(type);
    	RobotMap.chassisPIDchassisLeft3.enableBrakeMode(type);
    	
    	RobotMap.chassisPIDchassisRight1.enableBrakeMode(type);
    	RobotMap.chassisPIDchassisRight2.enableBrakeMode(type);
    	RobotMap.chassisPIDchassisRight3.enableBrakeMode(type);
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    	setDefaultCommand(new Chassis_TankDrive());
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        return driveEncoder.pidGet();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
    }

    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
        chassisLeft2.pidWrite(output);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
    }
}
